package com.template.perfecttemplatebot.enums;

public enum BotState {
    START,
    AMOUNT_OF_DAYS,
    REMOVE_ONE_DAY,
    MENU_3,
    LIST_OF_ALL_SUBSCRIPTIONS,
    LIST_OF_PAYED_SUBSCRIPTIONS,
    LIST_OF_EXPIRING_SUBSCRIPTIONS,
    LIST_OF_EXPIRED_SUBSCRIPTIONS,
    ADD_NEW_SUBSCRIPTION,
    SUB_MENU_1,
    SUB_MENU_2,
}
