package com.template.perfecttemplatebot.enums;

public enum BotState {
    ENTRANCE,
    AUTH,
    WAITING_ROOM,
    START,
    AMOUNT_OF_DAYS,
    REMOVE_ONE_DAY,
    MENU_3,
    LIST_OF_ALL_SUBSCRIPTIONS,
    LIST_OF_PAYED_SUBSCRIPTIONS,
    LIST_OF_EXPIRING_SUBSCRIPTIONS,
    LIST_OF_EXPIRED_SUBSCRIPTIONS,
    ADD_NEW_SUBSCRIPTION,
    RENEW_SUBSCRIPTION,
    CHECK_WAITING_ROOM,
    SET_DAYS,
    SUB_MENU,
    SUB_MENU_2

}
